services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=big_data
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
